# Generated by Django 4.0.4 on 2022-04-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('birth_date', models.DateField(max_length=10)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carts', models.ManyToManyField(related_name='carts', through='orders.Cart', to='products.product')),
                ('orders', models.ManyToManyField(related_name='orders', through='orders.Order', to='products.product')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
