# Generated by Django 4.0.4 on 2022-04-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_product',
            new_name='is_new',
        ),
    ]
