# Generated by Django 4.0.4 on 2022-04-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_new_product_product_is_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumnail_url',
            new_name='thumnail_url_1',
        ),
        migrations.AddField(
            model_name='category',
            name='detail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumnail_url_2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
