# Generated by Django 4.0.4 on 2022-05-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_thumnail_url_product_thumnail_url_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail_image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
