# Generated by Django 4.0.4 on 2022-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_thumnail_url_product_thumnail_url_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='detail',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
