# Generated by Django 4.0.4 on 2022-05-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_detail_image_url_product_is_best_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(default='Detail'),
        ),
    ]
